## Load in NumPy

In [2]:
import numpy as np

## The Basics

In [14]:
a = np.array([1, 2, 3, 4, 5], dtype='int16')
print(a)  

[1 2 3 4 5]


In [4]:
# make a 2D array of floats
b = np.array([[1.1, 2.2, 3.3, 4.4, 5.5], [6.6, 7.7, 8.8, 9.9, 10.0]])
print(b)

[[ 1.1  2.2  3.3  4.4  5.5]
 [ 6.6  7.7  8.8  9.9 10. ]]


In [11]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [12]:
# Get Shape
print(a.shape)
print(b.shape)

(5,)
(2, 5)


In [15]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float64


In [17]:
# Get Size in Bytes
print(a.itemsize)
print(b.itemsize)

2
8


In [18]:
# Get Total Size in Bytes
print(a.nbytes)
print(b.nbytes) 

10
80


## Accessing/Changing Specific Elements, rows, columns, etc

In [20]:
#create two dimensional np array of numbers from 1 to 14
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r,c]
c[1,5]

13

In [25]:
# Get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [29]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [51]:
# create a 2*3*3 np array
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [73]:
# Get a specific element [r,c,z]
print(d[0,1,1])
print('----')
print(d[0,1,:])
print('----')
print(d[0,0:3:2,:])
print('----')
print(d[0,0:3:2,2:])

5
----
[4 5 6]
----
[[1 2 3]
 [7 8 9]]
----
[[3]
 [9]]


## Initialize an different types of arrays

In [79]:
# All zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
# All ones
np.ones((4,2,2), dtype=np.int16)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [87]:
# Any Other Number
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [88]:
# Any Other Number
np.full_like(d, 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [89]:
# All random numbers
np.random.rand(4,2)

array([[0.49580158, 0.67879647],
       [0.86855418, 0.78201692],
       [0.01264266, 0.11195695],
       [0.94612846, 0.83959984]])

In [94]:
# Random Integers values
np.random.randint(-4,4,(3,3))

array([[ 3,  0, -3],
       [-2,  3, -2],
       [ 2, -4, -4]])

In [95]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [138]:
output = np.ones((5,5), dtype=np.int16)
s3 = np.zeros((3,3), dtype=np.int16)
s3[1,1] = 9
output[1:-1,1:-1] = s3
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Be careful when copying arrays**

In [142]:
#make one dimensional array 123
arr1 = np.array([1,2,3])
arr2 = arr1
arr3 = np.copy(arr1)
arr3[1] = 10
arr2[0] = 10
print(arr1)
print(arr2)
print(arr3)

[10  2  3]
[10  2  3]
[ 1 10  3]


## Mathematics

In [149]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [150]:
a+2

array([3, 4, 5, 6])

In [152]:
a - 2

array([-1,  0,  1,  2])

In [151]:
a * 2

array([2, 4, 6, 8])

In [153]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [154]:
b = np.array([[1,0,1,0]])
a+b

array([[2, 2, 4, 4]])

In [155]:
a**2

array([ 1,  4,  9, 16])

In [156]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [157]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [160]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [161]:
# find determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [162]:
# find inverse of a matrix
d = np.identity(3)
np.linalg.inv(d)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Statistics**

In [163]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
np.min(stats, axis=1)

array([1, 4])

In [168]:
np.max(stats)

6

In [169]:
np.sum(stats)

21

**Reorganizing arrays**

In [174]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = np.reshape(before, (2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [175]:
# Vertical Stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [176]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Miscellaneous

___Load Data from a File___

In [184]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[591, 669, 800,  55, 365, 561, 380, 648,  38,  53],
       [760,   1, 551, 981, 604,  60,  96, 432, 685, 263],
       [211, 789, 760, 625,  47, 587, 318, 777, 344,  62]])

___Boolean Masking and Advanced Indexing___

In [195]:
filedata > 600

array([[False,  True,  True, False, False, False, False,  True, False,
        False],
       [ True, False, False,  True,  True, False, False, False,  True,
        False],
       [False,  True,  True,  True, False, False, False,  True, False,
        False]])

In [194]:
filedata[filedata>600]

array([669, 800, 648, 760, 981, 604, 685, 789, 760, 625, 777])

In [196]:
# index with a list
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[0,1,7,8]]

array([1, 2, 8, 9])